name: Update README with Activity

on:
  schedule:
    - cron: '*/30 * * * *'  # Se ejecuta cada 30 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - uses: actions/checkout@v4
      
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'chore: Update README with recent activity'
          MAX_LINES: 5
